name: Issue Report
description: File a issue report
title: "[Bug]: "
labels: ["bug"]
project: ["Apollo7 issue tracking"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks Apollo7 team member for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true  
  - type: dropdown
    id: section
    attributes:
      label: What section are you seeing the problem on?
      multiple: true
      options:
        - Landing
        - Profile
        - Restaurant
        - Super Customer
        - NC
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Apollo 7 agreement.
      options:
        - label: I agree to follow Apollo 7's Code of Conduct
          required: true
